# Generated by Django 3.2.4 on 2021-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.PositiveIntegerField()),
                ('author_id', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=5000)),
                ('updated', models.CharField(max_length=20)),
                ('published', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('genres', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=20)),
                ('num_chapters', models.PositiveSmallIntegerField()),
                ('num_words', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('characters', models.CharField(max_length=500)),
                ('num_reviews', models.PositiveIntegerField()),
                ('num_favs', models.PositiveIntegerField()),
                ('num_follows', models.PositiveIntegerField()),
            ],
        ),
    ]
