# Generated by Django 3.2.4 on 2021-06-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeysuckleAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryFormatModel',
        ),
    ]
