# Generated by Django 3.2.3 on 2021-05-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['story_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
                ('tag_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=999, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profiles/default_profile_picture.png', null=True, upload_to='profiles/')),
                ('is_author', models.BooleanField(choices=[(True, 'Yes,I am.'), (False, 'Nope.')], default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='profiles.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=120, unique=True)),
                ('folder_desc', models.CharField(blank=True, max_length=512, null=True)),
                ('is_visible', models.BooleanField(choices=[(True, 'Visible'), (False, 'Invisible')], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Folders', to=settings.AUTH_USER_MODEL)),
                ('story', models.ManyToManyField(blank=True, null=True, to='profiles.Story')),
            ],
            options={
                'verbose_name_plural': 'Folders',
                'ordering': ['-created_at'],
            },
        ),
    ]
