# Generated by Django 3.2.3 on 2021-05-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-added_on'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='story_id',
            field=models.CharField(default='000000', max_length=30),
            preserve_default=False,
        ),
    ]
