# Generated by Django 3.2.4 on 2021-06-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210620_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilebadges',
            old_name='bages',
            new_name='badges',
        ),
    ]
