# Generated by Django 3.2.3 on 2021-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
