# Generated by Django 3.2.4 on 2021-06-14 04:19

import ckeditor.fields
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_folder_folder_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/default_profile_picture.png', null=True, upload_to=profiles.models.content_file_name),
        ),
    ]
