# Generated by Django 3.2.3 on 2021-05-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/default_profile_picture.png', null=True, upload_to='profiles/'),
        ),
    ]
