# Generated by Django 3.2.3 on 2021-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='story',
            field=models.ManyToManyField(to='profiles.Story'),
        ),
    ]
