# Generated by Django 3.2.3 on 2021-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_folder_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterField(
            model_name='folder',
            name='is_visible',
            field=models.BooleanField(choices=[(True, 'Visible'), (False, 'Invisible')], default=True),
        ),
    ]
