# Generated by Django 3.2.3 on 2021-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
